Merge Ring Attention into SFT Trainer
OpenRLHF/OpenRLHF pull request #477
Opened 2024-10-24 10:10 UTC by ZetangForward

2024-10-24 10:31 UTC, zhuzilin commented
Thank you for the PR. Could you run do a comparison run with and without the ring attention feature and shared the wandb?

2024-10-26 07:47 UTC, ZetangForward commented
@zhuzilin hi, my wandb is here, plz check out: https://wandb.ai/zecheng-tang/debug_openrlhf_train_sft/workspace?nw=nwuserzechengtang

Besides, I noticed a very important thing: **the loss accumulation logic seems strange in the raw code**:
https://github.com/OpenRLHF/OpenRLHF/blame/5f52e354829e402561313a8c56e0a5c071a3ae65/openrlhf/trainer/sft_trainer.py#L164

In fact, the normal logic for gradient accumulation should 
1. involve the loss being continuously accumulated through `self.strategy.backward`, and then updating the optimizer when `step % self.strategy.accumulated_gradients` is reached; 
2. At the same time, the gradient (loss) for each step should be divided by `accumulated_gradients` rather than directly propagating backward as in the original code

Here's a code snippet that illustrates the correct way to handle gradient accumulation:
```python
# Assuming self.strategy.accumulated_gradients is the number of steps to accumulate gradients
# and self.optimizer is the optimizer instance.

for step, batch in enumerate(train_loader):
    optimizer.zero_grad()
    outputs = model(batch)
    loss = criterion(outputs, targets)
    loss = loss / self.strategy.accumulated_gradients  # Normalize the loss
    self.strategy.backward(loss)  # Accumulate gradients
    if (step + 1) % self.strategy.accumulated_gradients == 0:
        optimizer.step()  # Update the optimizer
        optimizer.zero_grad()  # Reset gradients for the next accumulation cycle
```

When I tested, I found that the original code would cause a significant deviation when ring attention is turned on or off. The reason is that _when ring attention is turned on, there will inevitably be gradient accumulation (because a batch of data is not as much as vanilla attention), but using the original code would result in "fake gradient accumulation."

In my modified code, the result is the accumulation of gradients, which is why the vanilla loss and ring attention loss curves in wandb basically overlap.



This code snippet ensures that the gradients are accumulated over multiple steps and then normalized before updating the optimizer. This approach should help in reducing the discrepancy you observed when using ring attention.

I'm not sure if my understanding is correct, or if the DeepSpeed within the OpenRLHF library automatically handles the above operations (but upon reviewing the code, it seems like the logic mentioned above is not present). If there are any mistakes, please correct me.

Thank you.

@zhuzilin @tsaoyu

2024-10-26 08:53 UTC, zhuzilin requested changes

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/utils/utils.py
> +        train_data = train_data.select(range(keep_size))
I'm a little confused with the issue here, as the `train_dataloader` has already set with `drop_last=True`, which should serve the same function as the code added here.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +            # print(prompt_ids_len)
please recover the comment here.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +
please remove the newline added here to make the pr clean.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +from torch.nn import functional as F
please do `pre-commit install` before the commit, which will do auto formatting before commit. Also please recover the removed line here.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/cli/train_sft.py
> +        train_batch_size=args.train_batch_size,
This doesn't seem to be necessary, as the `blending_datasets` only serve as a function to blend datasets, and it should not require a `train_batch_size`.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +            keep_in_memory=False,
please remove the `keep_in_memory=False` which is not in the scope of this PR. If you hope to add this config, it will be nice to propose another PR that apply this change to all the `dataset.map`s.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +
same as above.

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/datasets/sft_dataset.py
> +        prompt_ids_lens, packed_seq_lens = [], []
please keep the origin code and add a newline for `packed_seq_lens`
```suggestion
        packed_seq_lens = []
```

2024-10-26 08:53 UTC, zhuzilin commented on openrlhf/trainer/sft_trainer.py
> +                    self.scheduler.step() # update learning rate
The scheduler and optimizer will be updated by deepspeed, please don't do the manual update.

2024-10-26 08:56 UTC, zhuzilin commented on openrlhf/trainer/sft_trainer.py
> +            accumulated_aux_loss = 0
these variables should be removed?

2024-10-26 10:13 UTC, catqaq commented
@ZetangForward thx.
For the ring attention for the SFT, Your implementation is essentially aligned with the SFT Vanilla implementation.
-> in a ring_attn_group, use total token loss/ total token num.
For gradient accumulation, DeepSpeed will handle it automatically. For the current progress, it's recommended that you temporarily remove the manual gradient accumulation implementation as @zhuzilin mentioned.

In fact, as long as gradient accumulation is used, there is an averaging among samples within the batch. If true token-level averaging is required, it’s necessary to bypass DeepSpeed's default gradient accumulation and manually use 'total token loss / total token num in a batch.' Of course, this is a completely separate matter, involving the differences between batch token average, sample token average, and then sample average, which we will discuss in depth later.

2024-10-26 10:31 UTC, catqaq requested changes

2024-10-26 10:31 UTC, catqaq commented on openrlhf/trainer/sft_trainer.py
> +                    gpt_loss = -torch.sum(gathered_logps) / num_calculate_tokens # compute loss on non-masked tokens
hi, num_calculate_tokens seems not defined?

2024-10-26 10:31 UTC, catqaq commented on openrlhf/trainer/sft_trainer.py
> +            accumulated_loss = 0
as @zhuzilin mentioned, if you don't want to do average in a batch, just remove it. Now, although the accumulated_loss is accumulated, it is not used afterward.

2024-10-26 10:41 UTC, ZetangForward commented on openrlhf/utils/utils.py
> +        train_data = train_data.select(range(keep_size))
I have already rolled back the files. Regarding the modifications to the framework, I will be opening a separate discussion. This will help ensure that our discussions remain focused and that all changes are well-documented and understood by the community.

2024-10-26 10:42 UTC, ZetangForward commented on openrlhf/datasets/sft_dataset.py
> +from torch.nn import functional as F
solved

2024-10-26 10:48 UTC, ZetangForward commented on openrlhf/trainer/sft_trainer.py
> +            accumulated_loss = 0
This variable is only utilized for logging, as the logs_dict in the original code can only log the loss in the minibatch, not work for accumulated_loss

```
logs_dict = {
                        "gpt_loss": gpt_loss.item(),
                        "loss_mean": loss_mean,
                        "lr": self.scheduler.get_last_lr()[0],
                    }
```

2024-10-26 11:21 UTC, ZetangForward commented
FYI @zhuzilin @catqaq 

Apologies for the previous PR, in which I introduced too many changes. 

I have since **rolled back the code to the main branch of OpenRLHF** and reverted the modifications related to loss accumulation, ensuring that the framework remains as close as possible to its original state.

Regarding gradient accumulation, I plan to raise this in **a discussion for further exploration.**

In this round of changes, I have made the necessary adjustments as per the requirements, and the behavior in wandb is consistent with what it was before.

2024-10-26 11:32 UTC, ZetangForward commented on openrlhf/cli/train_sft.py
> +        train_batch_size=args.train_batch_size,
already fix

2024-10-26 11:43 UTC, zhuzilin commented on openrlhf/trainer/sft_trainer.py
> +
the `step_bar.update()` has been updated below. And I suggest not adding `torch.cuda.empty_cache()` here by default because it will harm the performance.

2024-10-26 11:48 UTC, ZetangForward commented on openrlhf/trainer/sft_trainer.py
> +
already fix.

2024-10-26 11:52 UTC, catqaq commented
ok, thx
"Regarding gradient accumulation, I plan to raise this in a discussion for further exploration."  as I mentioned above, it's related to token average loss, we can discuss it later.

2024-10-26 11:54 UTC, zhuzilin approved these changes

2024-10-26 11:54 UTC, merged